//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Card_Id { get; set; }
        public Nullable<int> Validator_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Validator Validator { get; set; }
    }
}
